#include <linux/input.h> 

#define KEY_COUNT	12
#define KEY_GPIO_LIS {21,30,15,26,23,27,3,0,2,22,25,7}
#define KEY_VALUE_LIS {KEY_BACKSPACE,KEY_Q,KEY_W,KEY_DOWN,KEY_UP,KEY_T,KEY_ENTER,KEY_E,KEY_R,KEY_RIGHT,KEY_LEFT,KEY_Y}  
             
